---

- name: remove splash from boot screen
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
    line: 'GRUB_CMDLINE_LINUX_DEFAULT=""'
  register: grub_updated

- name: update grub
  ansible.builtin.shell: update-grub2
  args:
    executable: /bin/bash
  when: grub_updated.changed
